pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'Microsoft Partner Network'
    ScriptPath: 'WMMPLogicApps/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'WMMP'
    azurePowerShellVersion: LatestVersion
